version: '3'
services:
  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
  php:
    build: ./conf
    volumes:
      - ./code:/var/www/html
    entrypoint:
      - php-fpm
  nginx:
    image: nginx:alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./code:/var/www/html
    links:
      - php
    ports:
      - 8050:8050
  adminer:
    image: adminer
    ports:
      - 8080:8080
